-- Auto-generated from schema-map-postgres.psd1 (map@9d3471b)
-- engine: postgres
-- table:  replication_lag_samples
CREATE TABLE IF NOT EXISTS replication_lag_samples (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  peer_id BIGINT NOT NULL,
  metric TEXT NOT NULL,                         -- 'apply_lag_ms','transport_lag_ms'
  value BIGINT NOT NULL,
  captured_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_lag_metric CHECK (metric IN ('apply_lag_ms','transport_lag_ms'))
);
