-- Auto-generated from schema-map-postgres.yaml (map@sha1:FAEA49A5D5F8FAAD9F850D0F430ED451C5C1D707)
-- engine: postgres
-- table:  replication_lag_samples

CREATE TABLE IF NOT EXISTS replication_lag_samples (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  peer_id BIGINT NOT NULL,
  metric TEXT NOT NULL,                         -- 'apply_lag_ms','transport_lag_ms'
  value BIGINT NOT NULL,
  captured_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_lag_metric CHECK (metric IN ('apply_lag_ms','transport_lag_ms'))
);
